apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: todo-web-application-h2
  name: todo-web-application-h2
  namespace: default
spec:
  ports:
  - nodePort: 30702
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-web-application-h2
  sessionAffinity: ClientIP
  type: LoadBalancer