apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-08-24T11:59:40Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: todowebapp-h2
  name: todowebapp-h2
  namespace: default
  resourceVersion: "14289"
  uid: b1951657-1b74-4957-aafe-dda8f1d94b8e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.48.217
  clusterIPs:
  - 10.100.48.217
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32753
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todowebapp-h2
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: ab19516571b744957aafedda8f1d94b8-2106734037.ap-south-1.elb.amazonaws.com
